[workspace]
members = [
    "cli",
    "lib",
    "md",
    "md/macros",
    "md/macros/macros_derive",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
