name: Build

on:
  push:
    branches: 
      - main
    #tags:
    #  - 'v*.*.*'  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        binary-name: 
          - bjim
        target:  
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - aarch64-apple-darwin
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extension : ''
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            extension : ''
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            extension : '.exe'
          - os: macos-latest
            target: aarch64-apple-darwin
            extension : ''

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target ${{ matrix.target }}
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.binary-name }}-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/${{ matrix.binary-name }}${{ matrix.extension }}

